#!/bin/sh

DIRNAME=`dirname $0`

ARTIFACT=tupelo-shell

# The code version number is part of the main jar name.  Rather than
# hard-coding it here, we locate the jar with the LATEST version. Thus
# we always run the LATEST code, should many versions be present.

JARNAME=`ls target | grep $ARTIFACT | sort -n -r | head -1`
JARPATH=$DIRNAME/target/$JARNAME

PACKAGE=edu.uw.apl.tupelo.shell
#CLAZZ=Main
CLAZZ=JLine
#JAVA_OPTS="-Dlog4j.debug"

# Have to align the log4j.properties file with the jars.  
# Don't keep it in ./target (mvn clean!)
[ -d $DIRNAME/target ] && cp $DIRNAME/log4j.properties $DIRNAME/target/

# This codebase built using JDK 1.7 and requires a JRE 1.7 also...
exec java $JAVA_OPTS -classpath $JARPATH $PACKAGE.$CLAZZ "$@"

# eof
