#!/bin/sh

DIRNAME=`dirname $0`

ARTIFACT=tupelo-shell
VERSION=0.0.1
JAR=$ARTIFACT-$VERSION.jar
PACKAGE=edu.uw.apl.tupelo.shell
#CLAZZ=Main
CLAZZ=JLine
#JAVA_OPTS="-Dlog4j.debug"

# Have to align the log4j.properties file with the jars.  
# Don't keep it in ./target (mvn clean!)
[ -d $DIRNAME/target ] && cp $DIRNAME/log4j.properties $DIRNAME/target/

# This codebase built using JDK 1.7 and requires a JRE 1.7 also...
exec java $JAVA_OPTS -cp $DIRNAME/target/$JAR $PACKAGE.$CLAZZ "$@"

# eof
