#!/bin/sh

CLAZZ=$1
shift

ARTIFACT=tupelo-cli
VERSION=0.0.1
JAR=$ARTIFACT-$VERSION.jar
PACKAGE=edu.uw.apl.tupelo.cli

#JAVA_OPTS="-Dlog4j.debug"

# Have to align the log4j.properties file with the jars.  
# Don't keep it in ./target (mvn clean!)
[ -d target ] && cp log4j.properties target/

# This codebase built using JDK 1.7 and requires a JRE 1.7 also...
exec java $JAVA_OPTS -cp target/$JAR $PACKAGE.$CLAZZ "$@"

# eof
