#!/bin/sh

ARTIFACT=tupelo-cli
VERSION=0.0.1
JAR=$ARTIFACT-$VERSION.jar
PACKAGE=edu.uw.apl.tupelo.cli

CLAZZ=PutData

#echo `which java`

# This codebase built using JDK 1.7 and requires a JRE 1.7 also...
exec java -cp target/$JAR $PACKAGE.$CLAZZ "$@"

# eof
