#!/bin/sh

ARTIFACT=tupelo-amqp-objects

# The code version number is part of the main jar name.  Rather than
# hard-coding it here, we locate the jar with the LATEST version. Thus
# we always run the LATEST code, should many versions be present.

JARNAME=`ls target | grep $ARTIFACT | sort -n -r | head -1`
JARPATH=target/$JARNAME

PACKAGE=edu.uw.apl.tupelo.amqp.objects
CLAZZ=Info

exec java -classpath $JARPATH $PACKAGE.$CLAZZ "$@"

# eof
