#!/bin/bash

JARPATH=`dirname $0`/target

ARTIFACT=tupelo-amqp-server
VERSION=1.1.0

JAR=$ARTIFACT-$VERSION.jar
PACKAGE=edu.uw.apl.tupelo.amqp.server
CLAZZ=AMQPServer

exec java -classpath $JARPATH/$JAR $PACKAGE.$CLAZZ "$@"

# eof

