#!/bin/bash

ARTIFACT=tupelo-amqp-server
VERSION=0.0.1

JAR=target/$ARTIFACT-$VERSION.jar
PACKAGE=edu.uw.apl.tupelo.amqp.server
CLAZZ=AMQPServer

exec java -classpath $JAR $PACKAGE.$CLAZZ "$@"

# eof

