#!/bin/sh

DIRNAME=`dirname $0`

CLAZZ=$1
shift

ARTIFACT=tupelo-store-tools

# Locate latest versioned jar rather than hard-code one
JARNAME=`ls $DIRNAME/target | grep $ARTIFACT | sort -n -r | head -1`
JARPATH=$DIRNAME/target/$JARNAME

PACKAGE=edu.uw.apl.tupelo.store.tools

#JAVA_OPTS="-Dlog4j.debug"

# Have to align the log4j.properties file with the jars.  
# Don't keep it in ./target (mvn clean!)
[ -d $DIRNAME/target ] && cp $DIRNAME/log4j.properties $DIRNAME/target/

# This codebase built using JDK 1.7 and requires a JRE 1.7 also...
exec java $JAVA_OPTS -cp $JARPATH $PACKAGE.$CLAZZ "$@"

# eof
